-- Your SQL goes here
CREATE TABLE users (
  id VARCHAR PRIMARY KEY,
  username VARCHAR NOT NULL UNIQUE,
  password VARCHAR NOT NULL,
  email VARCHAR NOT NULL UNIQUE,
  registration_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)