[package]
name = "imagine-daggers"
version = "0.1.0"
authors = ["Zachary E Sohovich <zach@sneakycrow.dev>"]
edition = "2018"

[dependencies]
actix-web = "1.0.5"
actix-files = "0.1.4"
env_logger = "0.6.2"