[package]
name = "imagine-daggers"
version = "0.1.0"
authors = ["Zachary E Sohovich <zacharyesohovich@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "1.0.0"
diesel = "1.4.2"
dotenv = "0.14.1"